# Generated by Django 5.2.3 on 2025-07-21 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the space (e.g., 'Conference Room A')", max_length=200)),
                ('capacity', models.IntegerField(help_text='Maximum number of people the space can accommodate')),
                ('location', models.CharField(help_text='Physical location or address of the space', max_length=255)),
                ('image1', models.ImageField(blank=True, help_text='First image of the space', null=True, upload_to='space_images/')),
                ('image2', models.ImageField(blank=True, help_text='Second image of the space', null=True, upload_to='space_images/')),
                ('image3', models.ImageField(blank=True, help_text='Third image of the space', null=True, upload_to='space_images/')),
                ('is_booked', models.BooleanField(default=False, help_text='Indicates if the space is currently booked')),
            ],
            options={
                'verbose_name': 'Space',
                'verbose_name_plural': 'Spaces',
                'ordering': ['name'],
            },
        ),
    ]
